# Generated by Django 3.1.5 on 2021-06-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('gdate', models.CharField(default='default', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(default='default', max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team_score', models.IntegerField(default=0)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_goalie', models.CharField(blank=True, max_length=200)),
                ('home_team_goalie', models.CharField(blank=True, max_length=200)),
                ('away_team_goalie_sv', models.IntegerField(default=0)),
                ('home_team_goalie_sv', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_data', to='nhlserver.team')),
                ('game_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='nhlserver.date')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_data', to='nhlserver.team')),
            ],
        ),
    ]
